# Data Cleaning in Python
The examples and code in this notebook are taken from the [Kaggle Data Cleaning Challenge](https://www.kaggle.com/getting-started/52652)

Detailed explanations for important code snippets are provided by Mervat Abuelkheir as part of the CSEN1095 Data Engineering Course.

The goal of this notebook is to show how to handle missing values and noisy data.

Pay attention to the <span style="color:red"> <b> paragraphs in bold red</b></span>; they ask you to do something and provide input!

## Inspecting the data

First thing we need to do is import a dataset.

<br>We will work in this exercise with the <a href="https://www.kaggle.com/maxhorowitz/nflplaybyplay2009to2016#NFL%20Play%20by%20Play%202009-2017%20(v4).csv"> NFL dataset</a>. The NFL dataset is available in the repository's data folder, and is made available on Kaggle. It contains all the regular season plays from the 2009-2016 NFL seasons. The dataset has 100 columns. Each play contains information on: game situation, players involved, results, and advanced metrics such as expected point and win probability values.

### Important note

<b>The NFL dataset is very big (200+ MB) and is not made available in the `data` folder in this repository. Download the dataset from the link provided, store it in your own data or working directory, and proceed with running the code below, taking care to change your directory according to your own data storage location.</b>

<b>For large datasets, you will be provided with a link through which you can download the data. Another option is to read from the html link, provided the data is well-organized to help with proper parsing.</b>

In [3]:
# modules we'll use
import pandas as pd
import numpy as np

# read in all our data
nfl_data = pd.read_csv("data/NFL Play by Play 2009-2017 (v4).csv")

# set seed for reproducibility
np.random.seed(0)

In [4]:
# Look at a few rows of the nfl_data file. A handful of missing data!
nfl_data.sample(4)

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
244485,2014-10-26,2014102607,18,3,1.0,00:39,1,939.0,12.0,TB,...,1.240299,0.225647,0.774353,0.245582,0.754418,0.225647,0.019935,-0.018156,0.038091,2014
115340,2011-11-20,2011112000,22,4,1.0,06:47,7,407.0,44.0,OAK,...,NaN,0.056036,0.943964,0.042963,0.957037,0.943964,0.013073,NaN,NaN,2011
68357,2010-11-14,2010111401,8,2,NaN,00:23,1,1823.0,0.0,CLE,...,NaN,0.365307,0.634693,0.384697,0.615303,0.634693,-0.019390,NaN,NaN,2010
368377,2017-09-24,2017092405,24,4,1.0,08:48,9,528.0,8.0,CLE,...,1.075660,0.935995,0.064005,0.921231,0.078769,0.064005,0.014764,0.003866,0.010899,2017

## See how many missing data points we have

Let's see how many we have in each column. Let's start with the NFL dataset.

In [5]:
# get the number of missing data points per column
missing_values_count_nfl = nfl_data.isnull().sum()

# look at the # of missing points in the first ten columns
print(missing_values_count_nfl)

Date                                0
GameID                              0
Drive                               0
qtr                                 0
down                            61154
time                              224
TimeUnder                           0
TimeSecs                          224
PlayTimeDiff                      444
SideofField                       528
yrdln                             840
yrdline100                        840
ydstogo                             0
ydsnet                              0
GoalToGo                          840
FirstDown                       28811
posteam                         24992
DefensiveTeam                   24992
desc                                2
PlayAttempted                       0
Yards.Gained                        0
sp                                  0
Touchdown                           0
ExPointResult                  397578
TwoPointConv                   407083
DefTwoPoint                    407664
Safety                              0
Onsidekick                          0
PuntResult                     385317
PlayType                            0
                                ...
AwayTeam                            0
Timeout_Indicator                   0
Timeout_Team                        0
posteam_timeouts_pre                0
HomeTimeouts_Remaining_Pre          0
AwayTimeouts_Remaining_Pre          0
HomeTimeouts_Remaining_Post         0
AwayTimeouts_Remaining_Post         0
No_Score_Prob                     176
Opp_Field_Goal_Prob               176
Opp_Safety_Prob                   176
Opp_Touchdown_Prob                176
Field_Goal_Prob                   176
Safety_Prob                       176
Touchdown_Prob                    176
ExPoint_Prob                        0
TwoPoint_Prob                       0
ExpPts                            176
EPA                               369
airEPA                         248394
yacEPA                         248498
Home_WP_pre                     24954
Away_WP_pre                     24954
Home_WP_post                    26587
Away_WP_post                    26587
Win_Prob                        25009
WPA                              5541
airWPA                         248501
yacWPA                         248762
Season                              0
Length: 102, dtype: int64

There are a lot of missing values it seems! Let's take a look at the percentage of the missing values in the dataset.

In [6]:
# How many total missing values do we have?
# shape returns the dimentionality of a dataframe (rows and columns), can you guess what product will do?
total_cells_nfl = np.product(nfl_data.shape) 
total_missing_nfl = missing_values_count_nfl.sum()

# percent of data that is missing
percentage_missign_values_nfl = (total_missing_nfl/total_cells_nfl) * 100
print(percentage_missign_values_nfl)

24.87214126835169

Almost a quarter of the cells in this dataset are empty! 

In the next step, we're going to take a closer look at some of the columns with missing values and try to figure out what might be going on with them.

## Examining the missing values

This is the point where you should develop some data intuition and look at the data to try and figure out why it is the way it is and how that will affect your analysis. For dealing with missing values, you'll need to use your intution to figure out why the value is missing. One of the most important question you can ask yourself to help figure this out is this:

**Is this value missing becuase it wasn't recorded or becuase it dosen't exist?**

If a value is missing becuase it doens't exist (like the height of the oldest child of someone who doesn't have any children) then it doesn't make sense to try and guess what it might be. These values you probably do want to keep as `NaN`. On the other hand, if a value is missing becuase it wasn't recorded, then you can try to guess what it might have been based on the other values in that column and row. (This is called "imputation" and we'll learn how to do it next! :)

Let's work through an example. Looking at the number of missing values in the nfl_data dataframe, notice that the column TimesSec has a lot of missing values in it:

In [7]:
# look at the # of missing points in the first ten columns
missing_values_count_nfl[0:10]

Date                0
GameID              0
Drive               0
qtr                 0
down            61154
time              224
TimeUnder           0
TimeSecs          224
PlayTimeDiff      444
SideofField       528
dtype: int64

The `TimeSecs` column has information on the number of seconds left in the game when the play was made. This means that these values are probably missing because they were not recorded, rather than because they don't exist. So, it would make sense for us to try and guess what they should be rather than just leaving them as NA's.

On the other hand, there are other fields, like `PenalizedTeam` that also have lot of missing fields. In this case, though, the field is missing because if there was no penalty then it doesn't make sense to say which team was penalized. For this column, it would make more sense to either leave it empty or to add a third value like "neither" and use that to replace the NA's.

**Tip: This is a great place to read over the dataset documentation if you haven't already! If you're working with a dataset that you've gotten from another person, you can also try reaching out to them to get more information.**

You should look at each column individually to figure out the best strategy for filling those missing values. For the rest of this notebook, we'll cover some "quick and dirty" techniques that can help you with missing values but will probably also end up removing some useful information or adding some noise to your data.

## Dropping the missing values

If you don't have a reason to figure out why your values are missing, one option you have is to just remove any rows or columns that contain missing values. (Note: DO NOT do this approch for important projects! It's usually worth it to take the time to go through your data and really look at all the columns with missing values one-by-one to really get to know your dataset.)  

If you're sure you want to drop rows with missing values, pandas does have a handy function, `dropna()` to help you do this. Let's try it out on our NFL dataset!

In [8]:
# remove all the rows that contain a missing value
nfl_data.dropna()

Empty DataFrame
Columns: [Date, GameID, Drive, qtr, down, time, TimeUnder, TimeSecs, PlayTimeDiff, SideofField, yrdln, yrdline100, ydstogo, ydsnet, GoalToGo, FirstDown, posteam, DefensiveTeam, desc, PlayAttempted, Yards.Gained, sp, Touchdown, ExPointResult, TwoPointConv, DefTwoPoint, Safety, Onsidekick, PuntResult, PlayType, Passer, Passer_ID, PassAttempt, PassOutcome, PassLength, AirYards, YardsAfterCatch, QBHit, PassLocation, InterceptionThrown, Interceptor, Rusher, Rusher_ID, RushAttempt, RunLocation, RunGap, Receiver, Receiver_ID, Reception, ReturnResult, Returner, BlockingPlayer, Tackler1, Tackler2, FieldGoalResult, FieldGoalDistance, Fumble, RecFumbTeam, RecFumbPlayer, Sack, Challenge.Replay, ChalReplayResult, Accepted.Penalty, PenalizedTeam, PenaltyType, PenalizedPlayer, Penalty.Yards, PosTeamScore, DefTeamScore, ScoreDiff, AbsScoreDiff, HomeTeam, AwayTeam, Timeout_Indicator, Timeout_Team, posteam_timeouts_pre, HomeTimeouts_Remaining_Pre, AwayTimeouts_Remaining_Pre, HomeTimeouts_Remaining_Post, AwayTimeouts_Remaining_Post, No_Score_Prob, Opp_Field_Goal_Prob, Opp_Safety_Prob, Opp_Touchdown_Prob, Field_Goal_Prob, Safety_Prob, Touchdown_Prob, ExPoint_Prob, TwoPoint_Prob, ExpPts, EPA, airEPA, yacEPA, Home_WP_pre, Away_WP_pre, Home_WP_post, Away_WP_post, Win_Prob, WPA, airWPA, ...]
Index: []

[0 rows x 102 columns]

Oops! That's removed all our data! <span style="color:red"><b>Why do you think this happened?</b></span>

We might have better luck removing all the columns that have at least one missing value instead.

In [9]:
# Remove all columns with at least one missing value
columns_with_na_dropped = nfl_data.dropna(axis=1) # axis 1 indicates operation along columns
columns_with_na_dropped.head()

,Date,GameID,Drive,qtr,TimeUnder,ydstogo,ydsnet,PlayAttempted,Yards.Gained,sp,...,Timeout_Indicator,Timeout_Team,posteam_timeouts_pre,HomeTimeouts_Remaining_Pre,AwayTimeouts_Remaining_Pre,HomeTimeouts_Remaining_Post,AwayTimeouts_Remaining_Post,ExPoint_Prob,TwoPoint_Prob,Season
0,2009-09-10,2009091000,1,1,15,0,0,1,39,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
1,2009-09-10,2009091000,1,1,15,10,5,1,5,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
2,2009-09-10,2009091000,1,1,15,5,2,1,-3,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
3,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
4,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,0,None,3,3,3,3,3,0.0,0.0,2009

Let's check how much data we lost.

In [10]:
print("Columns in original dataset: %d \n" % nfl_data.shape[1])
print("Columns with na's dropped: %d" % columns_with_na_dropped.shape[1])

Columns in original dataset: 102

Columns with na's dropped: 41

We've lost quite a bit of data, but at this point we have successfully removed all the `NaN`'s from our data.

# Filling in missing values automatically

Another option is to try and fill in the missing values. Let's get a small sub-section of the NFL data so that it will print well and work with that to avoid having to work with the entire dataset and consume CPU time. You can work on the entire dataset at home!

In [11]:
# get a small subset of the NFL dataset
subset_nfl_data = nfl_data.loc[:, 'EPA':'Season'].head()
subset_nfl_data

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,NaN,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,-1.402760,NaN,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2.097796,NaN,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

We can use the Panda's fillna() function to fill in missing values in a dataframe for us. One option we have is to specify what we want the `NaN` values to be replaced with. Here, I'm saying that I would like to replace all the `NaN` values with 0.

In [12]:
# replace all NA's with 0
subset_nfl_data.fillna(0)

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,0.000000,0.000000,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,0.000000,0.000000,2009
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,-1.402760,0.000000,0.000000,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.000000,0.000000,2009
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2.097796,0.000000,0.000000,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,0.000000,0.000000,2009

We could also be a bit more savvy and replace missing values with whatever value comes directly after it in the same column. (This makes a lot of sense for datasets where the observations have some sort of logical order to them.)

In [13]:
# replace all NA's the value that comes directly after it in the same column, 
# then replace all the reamining na's with 0
subset_nfl_data.fillna(method = 'bfill', axis=0).fillna(0) # here you may want to explore other methods like 'mean' if it makes sense

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,-1.068169,1.146076,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,-0.032244,0.036899,2009
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,-1.402760,3.318841,-5.031425,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.106663,-0.156239,2009
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2.097796,0.000000,0.000000,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,0.000000,0.000000,2009

## Trying multivariate imputation with sklearn

sklearn has an `Imputer` and a `SimpleImputer` modules which perform imputation on one column at a time using the mean, median, or mode. 

sklearn also has a multivariate imputation module, `IterativeImputer`, that can help us impute values across multiple columns, but it is experimental and only available through developer release.

Let's see how an sklearn's imputation works for the NFL dataset.

In [14]:
from sklearn.preprocessing import Imputer
#from sklearn.impute import SimpleImputer # pretty much the same thing, you can try yourself
mean_imputer = Imputer(missing_values=np.nan, strategy='mean')
#mean_simpleimputer = SimpleImputer(missing_values=np.nan, strategy='mean') # Same use for sklearn SimpleImputer

# Again, let's get a small subset of the NFL dataset
subset_nfl_data = nfl_data.loc[:, 'EPA':'Season'].head()

# Check the presence of null values in the subset chosen
subset_nfl_data.isnull().sum()

H:\DataScienceWork\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

EPA             0
airEPA          3
yacEPA          3
Home_WP_pre     0
Away_WP_pre     0
Home_WP_post    0
Away_WP_post    0
Win_Prob        0
WPA             0
airWPA          3
yacWPA          3
Season          0
dtype: int64

In [15]:
# Now let's impute missing values in yacWPA column with the mean
mean_imputer.fit(subset_nfl_data[["yacWPA"]])
subset_nfl_data[["yacWPA"]]=mean_imputer.transform(subset_nfl_data[["yacWPA"]]).ravel()
#imputed_subset_nfl_data = pd.DataFrame(mean_simpleimputer.fit_transform(subset_nfl_data), columns=subset_nfl_data.columns) # fitting and transforming can be done in one step

# Let's check the presence null values again to see if imputation worked for the column
subset_nfl_data.isnull().sum()
# add you own counting of nulls for the dataframe imputed by SimpleImputer

EPA             0
airEPA          3
yacEPA          3
Home_WP_pre     0
Away_WP_pre     0
Home_WP_post    0
Away_WP_post    0
Win_Prob        0
WPA             0
airWPA          3
yacWPA          0
Season          0
dtype: int64

In [16]:
# Print the dataframe 
print(subset_nfl_data)
#print(imputed_subset_nfl_data) # if you want to try SimpleImputer code
# You may want to try the same code snippets above with the entire dataset and not just the subset

        EPA    airEPA    yacEPA  Home_WP_pre  Away_WP_pre  Home_WP_post  \
0  2.014474       NaN       NaN     0.485675     0.514325      0.546433
1  0.077907 -1.068169  1.146076     0.546433     0.453567      0.551088
2 -1.402760       NaN       NaN     0.551088     0.448912      0.510793
3 -1.712583  3.318841 -5.031425     0.510793     0.489207      0.461217
4  2.097796       NaN       NaN     0.461217     0.538783      0.558929

   Away_WP_post  Win_Prob       WPA    airWPA    yacWPA  Season
0      0.453567  0.485675  0.060758       NaN -0.059670    2009
1      0.448912  0.546433  0.004655 -0.032244  0.036899    2009
2      0.489207  0.551088 -0.040295       NaN -0.059670    2009
3      0.538783  0.510793 -0.049576  0.106663 -0.156239    2009
4      0.441071  0.461217  0.097712       NaN -0.059670    2009

Now let's try the more advanced `IterativeImputer` in sklearn. It provides means to do multivariate imputation using a variety of ML models.

In [17]:
# This code snippet may not work, so do not worry about it, and just examine the similarities with the SimpleImputer
# To use this experimental feature, we need to explicitly ask for it:
from sklearn.experimental import enable_iterative_imputer  
from sklearn.impute import IterativeImputer
from sklearn.linear_model import BayesianRidge # Imputation via linear regression
from sklearn.neighbors import KNeighborsRegressor # Imputation via KNN
# Define imputer
reg_imputer = IterativeImputer(BayesianRidge, max_iter=5, random_state=0)
subset_nfl_data = nfl_data.loc[:, 'EPA':'Season'].head()
imputed_subset_nfl_data = pd.DataFrame(mean_simpleimputer.fit_transform(subset_nfl_data), columns=subset_nfl_data.columns)
print(imputed_subset_nfl_data)

ModuleNotFoundError: No module named 'sklearn.experimental'

## <span style="color:red"> Exercise 1: Missing value handling on the San Francisco Building Permits Dataset </span>

<span style="color:red"><b> The <a href="https://www.kaggle.com/aparnashastry/building-permit-applications-data#Building_Permits.csv"> Building permits dataset</a> pertains to all types of structural permits from Jan 1, 2013-Feb 25th 2018 in San Francisco. Data includes details on application/permit numbers, job addresses, supervisorial districts, and the current status of the applications. A data dictionary for the dataset is available in the data folder in this repository.</b></span>

<span style="color:red"> <b>The dataset is rather big and does not exist in the "data" folder in this repository. Download the dataset from the link provided and store it in your own data or working folder. Import the dataset in the next cell, and work your way through the steps in the subsequent cells.</b></span>

In [1]:
import pandas as pd
import numpy as np

building_permits_ds = pd.read_csv("data/building-permit/Building_Permits.csv")
building_permits_ds.head()

/home/youssef/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (22,32) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992

<span style="color:red"> <b>Find out what percent of the building permits dataset is missing. </b></span>
<span style="color:red"> <b><br>Write down your code in the following cell. </b></span>

In [2]:
building_permits_ds.sample(10)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
105214,201511062022,8,otc alterations permit,11/06/2015,3702,054,1155,NaN,Market,St,...,1.0,constr type 1,1.0,constr type 1,NaN,6.0,South of Market,94103.0,"(37.779222586914074, -122.41340900261038)",1402510164321
177336,201706199725,8,otc alterations permit,04/27/2017,0032,001,240,NaN,Bay,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,North Beach,94133.0,"(37.80643669662406, -122.41087068803995)",1467457347247
22633,201308235081,8,otc alterations permit,08/23/2013,1920,019,1675,NaN,23rd,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,4.0,Sunset/Parkside,94122.0,"(37.756393350912475, -122.4812504802004)",1315293120484
66902,201411070962,8,otc alterations permit,11/07/2014,0227,048,555,NaN,Montgomery,St,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Chinatown,94111.0,"(37.79439328334235, -122.40343867496487)",1361666296981
132644,201608054321,8,otc alterations permit,08/05/2016,6149,002,1208,NaN,Bowdoin,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,9.0,Portola,94134.0,"(37.72079503695203, -122.40866292081574)",1432703196935
149383,201702099014,8,otc alterations permit,02/09/2017,3927,004,2500,NaN,16th,St,...,1.0,constr type 1,1.0,constr type 1,NaN,9.0,Mission,94103.0,"(37.76581701677373, -122.41196259484616)",1452787168070
116497,201603031162,8,otc alterations permit,03/03/2016,0922,020,2280,NaN,Bay,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,2.0,Marina,94123.0,"(37.801815040687686, -122.4445680626796)",141481584244
166886,201708023621,8,otc alterations permit,08/02/2017,3765,022,401,NaN,Harrison,St,...,1.0,constr type 1,1.0,constr type 1,NaN,6.0,Financial District/South Beach,94105.0,"(37.786065710349675, -122.3922287554256)",1472939481139
87433,201506017711,8,otc alterations permit,06/01/2015,0561,035,2530,NaN,Broadway,NaN,...,5.0,wood frame (5),5.0,wood frame (5),NaN,2.0,Pacific Heights,94123.0,"(37.79403402936833, -122.43876013291644)",1383478413127
173012,201605238133,3,additions alterations or repairs,05/23/2016,0189,012,1420,NaN,Jones,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94108.0,"(37.79441443073815, -122.4143649812999)",1424195232642

<span style="color:red"><b>Write a code to check the values of the `Street Number Suffix` and `Zipcode` from the building permits datasets. Both of these contain missing values. Which, if either, of these are missing because they don't exist? Which, if either, are missing because they weren't recorded?</b></span>

In [3]:
# get total of the missing building permits in the data set
missing_values = building_permits_ds.isnull().sum().sum()
total_cells_nfl = np.product(building_permits_ds.shape) 
percentage_missing_values = (missing_values/total_cells_nfl) * 100

# missing building permits percentage
percentage_missing_values

26.26002315058403

<span style="color:red"><b>See if you can drop the missing values from the building permits dataset and still keep some data, or drop the columns with missing values and see if you have columns still.</b></span>

In [4]:
data_set_na_dropped = building_permits_ds.dropna(axis=1)
data_set_na_dropped.head()

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Name,Current Status,Current Status Date,Filed Date,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,Ellis,expired,12/21/2017,05/06/2015,1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,Geary,issued,08/03/2017,04/19/2016,1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,Pacific,withdrawn,09/26/2017,05/27/2016,1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,Pacific,complete,07/24/2017,11/07/2016,1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,Market,issued,12/01/2017,11/28/2016,144548169992

In [5]:
print("Original data set columns: %d \n" % building_permits_ds.shape[1])
print("Dropped data set with dropped na columns: %d" % data_set_na_dropped.shape[1])

# we can see that 72% of the data is gone missing which is not a good approach as we lost so much data

Original data set columns: 43

Dropped data set with dropped na columns: 12

<span style="color:red"><b>Try replacing all the `NaN`'s in the building permits data with the one that comes directly after it and then replacing any remaining `NaN`'s with 0.</b></span>

In [19]:
building_permits_ds.fillna?

In [6]:
data_set_na_filled_next = building_permits_ds.fillna(method = 'bfill', axis=1)
data_set_na_filled_next

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,Ellis,Ellis,St,...,3,constr type 3,3,3,3,3,Tenderloin,94102,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,Geary,Geary,St,...,3,constr type 3,3,3,3,3,Tenderloin,94102,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,Pacific,Pacific,Av,...,1,constr type 1,1,constr type 1,3,3,Russian Hill,94109,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,Pacific,Pacific,Av,...,5,wood frame (5),5,wood frame (5),3,3,Nob Hill,94109,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,Market,Market,St,...,3,constr type 3,6,6,6,6,Tenderloin,94102,"(37.78315261897309, -122.40950883997789)",144548169992
5,201706149344,8,otc alterations permit,06/14/2017,4105,009,800,Indiana,Indiana,St,...,1,constr type 1,1,constr type 1,10,10,Potrero Hill,94107,"(37.75922331346539, -122.39170402628598)",1466911170855
6,201706300814,8,otc alterations permit,06/30/2017,1739,020,1291,11th,11th,Av,...,5,wood frame (5),5,wood frame (5),5,5,Inner Sunset,94122,"(37.764145640138565, -122.46875112470363)",1468970403692
7,M803667,8,otc alterations permit,06/30/2017,4789,014,1465,Revere,Revere,Av,...,10,10,10,10,10,10,Bayview Hunters Point,94124,"(37.73005099023611, -122.38784938916618)",1469035175050
8,M804227,8,otc alterations permit,07/05/2017,1212,054,2094,Fell,Fell,St,...,5,5,5,5,5,5,Lone Mountain/USF,94117,"(37.772393498502595, -122.45231466824669)",1469198253772
9,M804767,8,otc alterations permit,07/06/2017,1259,016,89,Alpine,Alpine,Tr,...,8,8,8,8,8,8,Haight Ashbury,94117,"(37.7691724293766, -122.43734859051908)",146932394171
10,M805287,8,otc alterations permit,07/06/2017,3541,001,106,Sanchez,Sanchez,St,...,8,8,8,8,8,8,Castro/Upper Market,94114,"(37.767349757757145, -122.43140682973024)",1469445246849
11,M805907,8,otc alterations permit,07/07/2017,0829,021,675,Fell,Fell,St,...,5,5,5,5,5,5,Hayes Valley,94102,"(37.774914087334544, -122.42886839796792)",146961582526
12,M806447,8,otc alterations permit,07/10/2017,6537,023,4082,25th,25th,St,...,8,8,8,8,8,8,Noe Valley,94114,"(37.75006779619502, -122.43127350268124)",1469781206718
13,201707252846,8,otc alterations permit,07/25/2017,6589,002R,681,27th,27th,St,...,5,wood frame (5),5,wood frame (5),8,8,Noe Valley,94131,"(37.7462205625642, -122.4353484860549)",1471799208305
14,M813729,8,otc alterations permit,07/26/2017,1049,027,2761,Pine,Pine,St,...,2,2,2,2,2,2,Pacific Heights,94115,"(37.78676200041077, -122.44124093333335)",147203988249
15,M813907,8,otc alterations permit,07/27/2017,0243,043,840,Powell,Powell,St,...,3,3,3,3,3,3,Chinatown,94108,"(37.7926690651263, -122.40883941791454)",147208763456
16,M813967,8,otc alterations permit,07/27/2017,0268,008,220,Montgomery,Montgomery,St,...,3,3,3,3,3,3,Financial District/South Beach,94104,"(37.79130641988351, -122.40198579459195)",147211866168
17,M814148,8,otc alterations permit,07/27/2017,3621,097,3707,21st,21st,St,...,8,8,8,8,8,8,Noe Valley,94114,"(37.75607840165479, -122.43041143390109)",1472184412108
18,201707283165,8,otc alterations permit,07/28/2017,0472,042,1307,Bay,Bay,St,...,5,wood frame (5),5,wood frame (5),2,2,Marina,94123,"(37.8035183252307, -122.42863180996076)",1472277302360
19,M814368,8,otc alterations permit,07/28/2017,2659,001,263,Corbett,Corbett,Av,...,8,8,8,8,8,8,Castro/Upper Market,94114,"(37.761092365437214, -122.44402154957145)",1472295408612
20,M814967,8,otc alterations permit,07/31/2017,1176,068,1624,Fulton,Fulton,St,...,5,5,5,5,5,5,Lone Mountain/USF,94117,"(37.77640228859421, -122.44361679686382)",1472619503582
21,201708013476,8,otc alterations permit,08/01/2017,6529,010,3410,26th,26th,St,...,5,wood frame (5),5,wood frame (5),9,9,Mission,94110,"(37.74914175355125, -122.41849211166853)",1472727381751
22,201708013544,3,additions alterations or repairs,08/01/2017,0074,043,2150,Taylor,Taylor,St,...,5,wood frame (5),5,wood frame (5),3,3,Russian Hill,94133,"(37.802405951667645, -122.41446286561653)",147281357792
23,M816927,8,otc alterations permit,08/07/2017,0941,012,2824,Filbert,Filbert,St,...,2,2,2,2,2,2,Marina,94123,"(37.79697456740493, -122.44615769723546)",147359384812
24,201708084249,8,otc alterations permit,08/08/2017,0542,039,1,Charlton,Charlton,Ct,...,5,wood frame (5),5,wood frame (5),2,2,Marina,94123,"(37.79739093461306, -122.43127133823367)",1473796372030
25,201708165014,8,otc alterations permit,08/16/2017,1824,006,1435,29th,29th,Av,...,5,wood frame (5),5,wood frame (5),4,4,Sunset/Parkside,94122,"(37.76052279949518, -122.4879889739165)",1474841115935
26,M820728,8,otc alterations permit,08/18/2017,1449,006,331,17th,17th,Av,...,1,1,1,1,1,1,Outer Richmond,94121,"(37.78177022745135, -122.47658979438802)",1475223100163
27,M821207,8,otc alterations permit,08/21/2017,1193,024,120,Shrader,Shrader,St,...,5,5,5,5,5,5,Lone Mountain/USF,94117,"(37.77371007080848, -122.45243180846707)",147537591942
28,M821268,8,otc alterations permit,08/21/2017,1851,012,1512,06th,06th,Av,...,7,7,7,7,7,7,Inner Sunset,94122,"(37.760252335082875, -122.4625393396095)",1475405117215
29,M821847,8,otc alterations permit,08/22/2017,0326,001,165,Powell,Powell,St,...,3,3,3,3,3,3,Tenderloin,94102,"(37.78625524960107, -122.40834431815433)",1475605447747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198870,M893328,8,otc alterations permit,02/23/2018,0025,024,888,North Point,North Point,St,...,2,2,2,2,2,2,Russian Hill,94109,"(37.8057495627139, -122.42181538597318)",1498327347381
198871,M893347,8,otc alterations permit,02/23/2018,1253,001,701,Clayton,Clayton,St,...,5,5,5,5,5,5,Haight Ashbury,94117,"(37.76869660680249, -122.44864582118123)",1498328241068
198872,201802232165,8,otc alterations permit,02/23/2018,3543,012,2123,Market,Market,St,...,5,wood frame (5),5,wood frame (5),8,8,Castro/Upper Market,94114,"(37.76682151637876, -122.42926240167795)",1498329423799
198873,201802232166,8,otc alterations permit,02/23/2018,5723,041,100,Tompkins,Tompkins,Av,...,5,wood frame (5),5,wood frame (5),9,9,Bernal Heights,94110,"(37.73708421334594, -122.4157759256698)",1498330475722
198874,201802232106,8,otc alterations permit,02/23/2018,6592,023,336,Duncan,Duncan,St,...,5,wood frame (5),5,wood frame (5),8,8,Noe Valley,94131,"(37.746231746880696, -122.4285179313817)",1498331399024
198875,201802232167,8,otc alterations permit,02/23/2018,0807,010,580,Hayes,Hayes,St,...,1,1,1,constr type 1,5,5,Hayes Valley,94102,"(37.776756688343944, -122.4260292019233)",149833282001
198876,M893367,8,otc alterations permit,02/23/2018,1213,013,500,Stanyan,Stanyan,St,...,5,5,5,5,5,5,Lone Mountain/USF,94117,"(37.77277103274044, -122.45392960440346)",149833392632
198877,201802232169,8,otc alterations permit,02/23/2018,7103,020,91,Lobos,Lobos,St,...,5,wood frame (5),5,wood frame (5),11,11,Oceanview/Merced/Ingleside,94112,"(37.7146765393289, -122.45557353560899)",1498334221586
198878,201802232170,8,otc alterations permit,02/23/2018,3641,016,3134,24th,24th,St,...,5,wood frame (5),5,wood frame (5),9,9,Mission,94110,"(37.752661001157854, -122.41485533400166)",1498335409431
198879,201802232171,8,otc alterations permit,02/23/2018,6082,009,350,Paris,Paris,St,...,5,wood frame (5),5,wood frame (5),11,11,Excelsior,94112,"(37.72324934238285, -122.43409219261636)",1498336195616
198880,M893387,8,otc alterations permit,02/23/2018,1841,025D,1442,Funston,Funston,Av,...,7,7,7,7,7,7,Inner Sunset,94122,"(37.76117190796411, -122.47007880106999)",1498337116842
198881,M893407,8,otc alterations permit,02/23/2018,0018,004,2300,Stockton,Stockton,St,...,3,3,3,3,3,3,North Beach,94133,"(37.80747140583783, -122.41024025753224)",1498338347099
198882,201802232172,8,otc alterations permit,02/23/2018,6021,001B,730,Excelsior,Excelsior,Av,...,5,wood frame (5),5,wood frame (5),11,11,Excelsior,94112,"(37.723206757170836, -122.42763728105176)",1498339194341
198883,M893427,8,otc alterations permit,02/23/2018,0315,021,377,Geary,Geary,St,...,3,3,3,3,3,3,Tenderloin,94102,"(37.78696971667916, -122.40936701144197)",149834069380
198884,M893447,8,otc alterations permit,02/23/2018,3504,030,1699,Market,Market,St,...,6,6,6,6,6,6,Mission,94103,"(37.77217130976155, -122.42193576313322)",1498341156230
198885,201802232173,8,otc alterations permit,02/23/2018,2150,001A,2007,30th,30th,Av,...,5,wood frame (5),5,wood frame (5),4,4,Sunset/Parkside,94116,"(37.74976582284573, -122.48824447038214)",1498342127659
198886,201709066971,3,additions alterations or repairs,09/06/2017,0999,025,3191,Washington,Washington,St,...,5,wood frame (5),5,wood frame (5),1477559238559,1477559238559,1477559238559,1477559238559,1477559238559,1477559238559
198887,201710040362,8,otc alterations permit,10/04/2017,0750,001,1521,Eddy,Eddy,St,...,1,constr type 1,1,constr type 1,1482126434174,1482126434174,1482126434174,1482126434174,1482126434174,1482126434174
198888,201710110995,8,otc alterations permit,10/11/2017,0726,019,1410,Steiner,Steiner,St,...,1,constr type 1,1,constr type 1,1483035367814,1483035367814,1483035367814,1483035367814,1483035367814,1483035367814
198889,201710242114,8,otc alterations permit,10/24/2017,1654,035,748,12th,12th,Av,...,5,wood frame (5),5,wood frame (5),1484587273155,1484587273155,1484587273155,1484587273155,1484587273155,1484587273155
198890,201711274822,3,additions alterations or repairs,11/27/2017,3803,001,185,Berry,Berry,St,...,1,constr type 1,1,constr type 1,1488352388160,1488352388160,1488352388160,1488352388160,1488352388160,1488352388160
198891,201711274844,8,otc alterations permit,11/27/2017,0766,008,590,Van Ness,Van Ness,Av,...,3,constr type 3,3,constr type 3,148838081446,148838081446,148838081446,148838081446,148838081446,148838081446
198892,201712045380,8,otc alterations permit,12/04/2017,1180,021,1543,Mcallister,Mcallister,St,...,5,wood frame (5),5,wood frame (5),148916691540,148916691540,148916691540,148916691540,148916691540,148916691540
198893,201712055472,8,otc alterations permit,12/05/2017,1000,014,3018,Clay,Clay,St,...,5,wood frame (5),5,wood frame (5),1489281258414,1489281258414,1489281258414,1489281258414,1489281258414,1489281258414
198894,201712055493,8,otc alterations permit,12/05/2017,3522,006,340,12th,12th,St,...,5,wood frame (5),5,wood frame (5),1489308256860,1489308256860,1489308256860,1489308256860,1489308256860,1489308256860
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,Montgomery,Montgomery,St,...,1489337276729,1489337276729,1489337276729,1489337276729,1489337276729,1489337276729,1489337276729,1489337276729,1489337276729,1489337276729
198896,201712055595,8,otc alterations permit,12/05/2017,0271,014,580,Bush,Bush,St,...,5,wood frame (5),5,wood frame (5),1489462354993,1489462354993,1489462354993,1489462354993,1489462354993,1489462354993
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,Indiana,Indiana,St,...,1489539379952,1489539379952,1489539379952,1489539379952,1489539379952,1489539379952,1489539379952,1489539379952,1489539379952,1489539379952
198898,M863747,8,otc alterations permit,12/06/2017,0298,029,795,Sutter,Sutter,St,...,1489608233656,1489608233656,1489608233656,1489608233656,1489608233656,1489608233656,1489608233656,1489608233656,1489608233656,1489608233656
198899,M864287,8,otc alterations permit,12/07/2017,0160,006,838,Pacific,Pacific,Av,...,1489796283803,1489796283803,1489796283803,1489796283803,1489796283803,1489796283803,1489796283803,1489796283803,1489796283803,1489796283803

In [7]:
data_set_na_filled_zero = building_permits_ds.fillna(0)
data_set_na_filled_zero

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,0,Ellis,St,...,3.0,constr type 3,0.0,0,0,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,0,Geary,St,...,3.0,constr type 3,0.0,0,0,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,0,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,0,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,0,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),0,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,0,Market,St,...,3.0,constr type 3,0.0,0,0,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992
5,201706149344,8,otc alterations permit,06/14/2017,4105,009,800,0,Indiana,St,...,1.0,constr type 1,1.0,constr type 1,0,10.0,Potrero Hill,94107.0,"(37.75922331346539, -122.39170402628598)",1466911170855
6,201706300814,8,otc alterations permit,06/30/2017,1739,020,1291,0,11th,Av,...,5.0,wood frame (5),5.0,wood frame (5),0,5.0,Inner Sunset,94122.0,"(37.764145640138565, -122.46875112470363)",1468970403692
7,M803667,8,otc alterations permit,06/30/2017,4789,014,1465,0,Revere,Av,...,0.0,0,0.0,0,0,10.0,Bayview Hunters Point,94124.0,"(37.73005099023611, -122.38784938916618)",1469035175050
8,M804227,8,otc alterations permit,07/05/2017,1212,054,2094,0,Fell,St,...,0.0,0,0.0,0,0,5.0,Lone Mountain/USF,94117.0,"(37.772393498502595, -122.45231466824669)",1469198253772
9,M804767,8,otc alterations permit,07/06/2017,1259,016,89,0,Alpine,Tr,...,0.0,0,0.0,0,0,8.0,Haight Ashbury,94117.0,"(37.7691724293766, -122.43734859051908)",146932394171
10,M805287,8,otc alterations permit,07/06/2017,3541,001,106,0,Sanchez,St,...,0.0,0,0.0,0,0,8.0,Castro/Upper Market,94114.0,"(37.767349757757145, -122.43140682973024)",1469445246849
11,M805907,8,otc alterations permit,07/07/2017,0829,021,675,0,Fell,St,...,0.0,0,0.0,0,0,5.0,Hayes Valley,94102.0,"(37.774914087334544, -122.42886839796792)",146961582526
12,M806447,8,otc alterations permit,07/10/2017,6537,023,4082,0,25th,St,...,0.0,0,0.0,0,0,8.0,Noe Valley,94114.0,"(37.75006779619502, -122.43127350268124)",1469781206718
13,201707252846,8,otc alterations permit,07/25/2017,6589,002R,681,0,27th,St,...,5.0,wood frame (5),5.0,wood frame (5),0,8.0,Noe Valley,94131.0,"(37.7462205625642, -122.4353484860549)",1471799208305
14,M813729,8,otc alterations permit,07/26/2017,1049,027,2761,0,Pine,St,...,0.0,0,0.0,0,0,2.0,Pacific Heights,94115.0,"(37.78676200041077, -122.44124093333335)",147203988249
15,M813907,8,otc alterations permit,07/27/2017,0243,043,840,0,Powell,St,...,0.0,0,0.0,0,0,3.0,Chinatown,94108.0,"(37.7926690651263, -122.40883941791454)",147208763456
16,M813967,8,otc alterations permit,07/27/2017,0268,008,220,0,Montgomery,St,...,0.0,0,0.0,0,0,3.0,Financial District/South Beach,94104.0,"(37.79130641988351, -122.40198579459195)",147211866168
17,M814148,8,otc alterations permit,07/27/2017,3621,097,3707,0,21st,St,...,0.0,0,0.0,0,0,8.0,Noe Valley,94114.0,"(37.75607840165479, -122.43041143390109)",1472184412108
18,201707283165,8,otc alterations permit,07/28/2017,0472,042,1307,0,Bay,St,...,5.0,wood frame (5),5.0,wood frame (5),0,2.0,Marina,94123.0,"(37.8035183252307, -122.42863180996076)",1472277302360
19,M814368,8,otc alterations permit,07/28/2017,2659,001,263,0,Corbett,Av,...,0.0,0,0.0,0,0,8.0,Castro/Upper Market,94114.0,"(37.761092365437214, -122.44402154957145)",1472295408612
20,M814967,8,otc alterations permit,07/31/2017,1176,068,1624,0,Fulton,St,...,0.0,0,0.0,0,0,5.0,Lone Mountain/USF,94117.0,"(37.77640228859421, -122.44361679686382)",1472619503582
21,201708013476,8,otc alterations permit,08/01/2017,6529,010,3410,0,26th,St,...,5.0,wood frame (5),5.0,wood frame (5),0,9.0,Mission,94110.0,"(37.74914175355125, -122.41849211166853)",1472727381751
22,201708013544,3,additions alterations or repairs,08/01/2017,0074,043,2150,0,Taylor,St,...,5.0,wood frame (5),5.0,wood frame (5),0,3.0,Russian Hill,94133.0,"(37.802405951667645, -122.41446286561653)",147281357792
23,M816927,8,otc alterations permit,08/07/2017,0941,012,2824,0,Filbert,St,...,0.0,0,0.0,0,0,2.0,Marina,94123.0,"(37.79697456740493, -122.44615769723546)",147359384812
24,201708084249,8,otc alterations permit,08/08/2017,0542,039,1,0,Charlton,Ct,...,5.0,wood frame (5),5.0,wood frame (5),0,2.0,Marina,94123.0,"(37.79739093461306, -122.43127133823367)",1473796372030
25,201708165014,8,otc alterations permit,08/16/2017,1824,006,1435,0,29th,Av,...,5.0,wood frame (5),5.0,wood frame (5),0,4.0,Sunset/Parkside,94122.0,"(37.76052279949518, -122.4879889739165)",1474841115935
26,M820728,8,otc alterations permit,08/18/2017,1449,006,331,0,17th,Av,...,0.0,0,0.0,0,0,1.0,Outer Richmond,94121.0,"(37.78177022745135, -122.47658979438802)",1475223100163
27,M821207,8,otc alterations permit,08/21/2017,1193,024,120,0,Shrader,St,...,0.0,0,0.0,0,0,5.0,Lone Mountain/USF,94117.0,"(37.77371007080848, -122.45243180846707)",147537591942
28,M821268,8,otc alterations permit,08/21/2017,1851,012,1512,0,06th,Av,...,0.0,0,0.0,0,0,7.0,Inner Sunset,94122.0,"(37.760252335082875, -122.4625393396095)",1475405117215
29,M821847,8,otc alterations permit,08/22/2017,0326,001,165,0,Powell,St,...,0.0,0,0.0,0,0,3.0,Tenderloin,94102.0,"(37.78625524960107, -122.40834431815433)",1475605447747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198870,M893328,8,otc alterations permit,02/23/2018,0025,024,888,0,North Point,St,...,0.0,0,0.0,0,0,2.0,Russian Hill,94109.0,"(37.8057495627139, -122.42181538597318)",1498327347381
198871,M893347,8,otc alterations permit,02/23/2018,1253,001,701,0,Clayton,St,...,0.0,0,0.0,0,0,5.0,Haight Ashbury,94117.0,"(37.76869660680249, -122.44864582118123)",1498328241068
198872,201802232165,8,otc alterations permit,02/23/2018,3543,012,2123,0,Market,St,...,5.0,wood frame (5),5.0,wood frame (5),0,8.0,Castro/Upper Market,94114.0,"(37.76682151637876, -122.42926240167795)",1498329423799
198873,201802232166,8,otc alterations permit,02/23/2018,5723,041,100,0,Tompkins,Av,...,5.0,wood frame (5),5.0,wood frame (5),0,9.0,Bernal Heights,94110.0,"(37.73708421334594, -122.4157759256698)",1498330475722
198874,201802232106,8,otc alterations permit,02/23/2018,6592,023,336,0,Duncan,St,...,5.0,wood frame (5),5.0,wood frame (5),0,8.0,Noe Valley,94131.0,"(37.746231746880696, -122.4285179313817)",1498331399024
198875,201802232167,8,otc alterations permit,02/23/2018,0807,010,580,0,Hayes,St,...,0.0,0,1.0,constr type 1,0,5.0,Hayes Valley,94102.0,"(37.776756688343944, -122.4260292019233)",149833282001
198876,M893367,8,otc alterations permit,02/23/2018,1213,013,500,0,Stanyan,St,...,0.0,0,0.0,0,0,5.0,Lone Mountain/USF,94117.0,"(37.77277103274044, -122.45392960440346)",149833392632
198877,201802232169,8,otc alterations permit,02/23/2018,7103,020,91,0,Lobos,St,...,5.0,wood frame (5),5.0,wood frame (5),0,11.0,Oceanview/Merced/Ingleside,94112.0,"(37.7146765393289, -122.45557353560899)",1498334221586
198878,201802232170,8,otc alterations permit,02/23/2018,3641,016,3134,0,24th,St,...,5.0,wood frame (5),5.0,wood frame (5),0,9.0,Mission,94110.0,"(37.752661001157854, -122.41485533400166)",1498335409431
198879,201802232171,8,otc alterations permit,02/23/2018,6082,009,350,0,Paris,St,...,5.0,wood frame (5),5.0,wood frame (5),0,11.0,Excelsior,94112.0,"(37.72324934238285, -122.43409219261636)",1498336195616
198880,M893387,8,otc alterations permit,02/23/2018,1841,025D,1442,0,Funston,Av,...,0.0,0,0.0,0,0,7.0,Inner Sunset,94122.0,"(37.76117190796411, -122.47007880106999)",1498337116842
198881,M893407,8,otc alterations permit,02/23/2018,0018,004,2300,0,Stockton,St,...,0.0,0,0.0,0,0,3.0,North Beach,94133.0,"(37.80747140583783, -122.41024025753224)",1498338347099
198882,201802232172,8,otc alterations permit,02/23/2018,6021,001B,730,0,Excelsior,Av,...,5.0,wood frame (5),5.0,wood frame (5),0,11.0,Excelsior,94112.0,"(37.723206757170836, -122.42763728105176)",1498339194341
198883,M893427,8,otc alterations permit,02/23/2018,0315,021,377,0,Geary,St,...,0.0,0,0.0,0,0,3.0,Tenderloin,94102.0,"(37.78696971667916, -122.40936701144197)",149834069380
198884,M893447,8,otc alterations permit,02/23/2018,3504,030,1699,0,Market,St,...,0.0,0,0.0,0,0,6.0,Mission,94103.0,"(37.77217130976155, -122.42193576313322)",1498341156230
198885,201802232173,8,otc alterations permit,02/23/2018,2150,001A,2007,0,30th,Av,...,5.0,wood frame (5),5.0,wood frame (5),0,4.0,Sunset/Parkside,94116.0,"(37.74976582284573, -122.48824447038214)",1498342127659
198886,201709066971,3,additions alterations or repairs,09/06/2017,0999,025,3191,0,Washington,St,...,5.0,wood frame (5),5.0,wood frame (5),0,0.0,0,0.0,0,1477559238559
198887,201710040362,8,otc alterations permit,10/04/2017,0750,001,1521,0,Eddy,St,...,1.0,constr type 1,1.0,constr type 1,0,0.0,0,0.0,0,1482126434174
198888,201710110995,8,otc alterations permit,10/11/2017,0726,019,1410,0,Steiner,St,...,1.0,constr type 1,1.0,constr type 1,0,0.0,0,0.0,0,1483035367814
198889,201710242114,8,otc alterations permit,10/24/2017,1654,035,748,0,12th,Av,...,5.0,wood frame (5),5.0,wood frame (5),0,0.0,0,0.0,0,1484587273155
198890,201711274822,3,additions alterations or repairs,11/27/2017,3803,001,185,0,Berry,St,...,1.0,constr type 1,1.0,constr type 1,0,0.0,0,0.0,0,1488352388160
198891,201711274844,8,otc alterations permit,11/27/2017,0766,008,590,0,Van Ness,Av,...,3.0,constr type 3,3.0,constr type 3,0,0.0,0,0.0,0,148838081446
198892,201712045380,8,otc alterations permit,12/04/2017,1180,021,1543,0,Mcallister,St,...,5.0,wood frame (5),5.0,wood frame (5),0,0.0,0,0.0,0,148916691540
198893,201712055472,8,otc alterations permit,12/05/2017,1000,014,3018,0,Clay,St,...,5.0,wood frame (5),5.0,wood frame (5),0,0.0,0,0.0,0,1489281258414
198894,201712055493,8,otc alterations permit,12/05/2017,3522,006,340,0,12th,St,...,5.0,wood frame (5),5.0,wood frame (5),0,0.0,0,0.0,0,1489308256860
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,0,Montgomery,St,...,0.0,0,0.0,0,0,0.0,0,0.0,0,1489337276729
198896,201712055595,8,otc alterations permit,12/05/2017,0271,014,580,0,Bush,St,...,5.0,wood frame (5),5.0,wood frame (5),0,0.0,0,0.0,0,1489462354993
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,0,Indiana,St,...,0.0,0,0.0,0,0,0.0,0,0.0,0,1489539379952
198898,M863747,8,otc alterations permit,12/06/2017,0298,029,795,0,Sutter,St,...,0.0,0,0.0,0,0,0.0,0,0.0,0,1489608233656
198899,M864287,8,otc alterations permit,12/07/2017,0160,006,838,0,Pacific,Av,...,0.0,0,0.0,0,0,0.0,0,0.0,0,1489796283803

<span style="color:red"><b>Create a new dataset at the ending with all missing values handled and store as a CSV file.</b></span>

In [8]:
data_set_na_filled_zero.to_csv('data/building-permit/Building_Permits.new-data.csv')

## <span style="color:red"> Exercise 2: Missing value handling on the  Pima Indians Diabetes Dataset</span>

<span style="color:red"><b> The <a href= "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"> Pima Indians Diabetes Dataset</a> involves predicting the onset of diabetes within 5 years in Pima Indians given medical details.</b></span>

<span style="color:red">There are 768 observations with 8 input variables and 1 output variable. The variable names are as follows:</span>

<br><span style="color:red">0. Number of times pregnant.</span>
<br><span style="color:red">1. Plasma glucose concentration a 2 hours in an oral glucose tolerance test.</span>
<br><span style="color:red">2. Diastolic blood pressure (mm Hg).</span>
<br><span style="color:red">3. Triceps skinfold thickness (mm).</span>
<br><span style="color:red">4. 2-Hour serum insulin (mu U/ml).</span>
<br><span style="color:red">5. Body mass index (weight in kg/(height in m)^2).</span>
<br><span style="color:red">6. Diabetes pedigree function.</span>
<br><span style="color:red">7. Age (years).
<br><span style="color:red">8. Class variable (0 or 1).</span>

<span style="color:red"> <b>This is a medical dataset, so an important thing we will do with this dataset is that we will see if the statistical summaries can reveal something about the missing values.</b></span>

<span style="color:red"> <b>The dataset is available in the `data` folder in this repository. Import the dataset in the next cell, and work your way through the steps in the subsequent cells.</b></span>

In [15]:
import pandas as pd
import numpy as np
columns = ["pregnant_times", 
    "glucose_conc", 
    "blood_pressure", 
    "triceps_thickness", 
    "serum_insulin", 
    "bmi", 
    "diabetes_pedigree", 
    "age", 
    "class_variable"]
pima_indians_ds = pd.read_csv("data/pima-indians-diabetes.data.csv", header=None, names=columns)
pima_indians_ds.head()

,pregnant_times,glucose_conc,blood_pressure,triceps_thickness,serum_insulin,bmi,diabetes_pedigree,age,class_variable
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

<span style="color:red"> <b>Use the describe method used for pandas data frames to obtain a statistucal summary of the dataset.</b></span>

In [10]:
pima_indians_ds.describe()

,pregnant_times,glucose_conc,blood_pressure,triceps_thickness,serum_insulin,bmi,diabetes_pedigree,age,class_variable
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

<span style="color:red"><b>There are columns that have a minimum value of zero (0). On some columns, a value of zero does not make sense and indicates an invalid or missing value. For example, the `BMI` for a person cannot be 0. See if there are other columns/attributes whose value of 0 does not make sense. An understanding of the medical columns may be needed.</b></span>

In [11]:
pima_indians_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
pregnant_times       768 non-null int64
glucose_conc         768 non-null int64
blood_pressure       768 non-null int64
triceps_thickness    768 non-null int64
serum_insulin        768 non-null int64
bmi                  768 non-null float64
diabetes_pedigree    768 non-null float64
age                  768 non-null int64
class_variable       768 non-null int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

<span style="color:red"><b>Now you can proceed to check the missing values and remove/impute as in exercise 1. Create a new dataset at the ending with all missing values handled and store as a CSV file.</b></span>

In [12]:
pima_indians_ds.blood_pressure.replace(0, pima_indians_ds.mean().blood_pressure, inplace = True)
pima_indians_ds.triceps_thickness.replace(0, pima_indians_ds.mean().triceps_thickness, inplace = True)
pima_indians_ds.serum_insulin.replace(0, pima_indians_ds.mean().serum_insulin, inplace = True)
pima_indians_ds.bmi.replace(0, pima_indians_ds.mean().bmi, inplace = True)
pima_indians_ds.age.replace(0, pima_indians_ds.mean().age, inplace = True)
pima_indians_ds.head()

,pregnant_times,glucose_conc,blood_pressure,triceps_thickness,serum_insulin,bmi,diabetes_pedigree,age,class_variable
0,6,148,72.000000,35.000000,79.799479,33.600000,0.627,50,1
1,1,85,66.000000,29.000000,79.799479,26.600000,0.351,31,0
2,8,183,64.000000,20.536458,79.799479,23.300000,0.672,32,1
3,1,89,66.000000,23.000000,94.000000,28.100000,0.167,21,0
4,0,137,40.000000,35.000000,168.000000,43.100000,2.288,33,1
5,5,116,74.000000,20.536458,79.799479,25.600000,0.201,30,0
6,3,78,50.000000,32.000000,88.000000,31.000000,0.248,26,1
7,10,115,69.105469,20.536458,79.799479,35.300000,0.134,29,0
8,2,197,70.000000,45.000000,543.000000,30.500000,0.158,53,1
9,8,125,96.000000,20.536458,79.799479,31.992578,0.232,54,1
10,4,110,92.000000,20.536458,79.799479,37.600000,0.191,30,0
11,10,168,74.000000,20.536458,79.799479,38.000000,0.537,34,1
12,10,139,80.000000,20.536458,79.799479,27.100000,1.441,57,0
13,1,189,60.000000,23.000000,846.000000,30.100000,0.398,59,1
14,5,166,72.000000,19.000000,175.000000,25.800000,0.587,51,1
15,7,100,69.105469,20.536458,79.799479,30.000000,0.484,32,1
16,0,118,84.000000,47.000000,230.000000,45.800000,0.551,31,1
17,7,107,74.000000,20.536458,79.799479,29.600000,0.254,31,1
18,1,103,30.000000,38.000000,83.000000,43.300000,0.183,33,0
19,1,115,70.000000,30.000000,96.000000,34.600000,0.529,32,1
20,3,126,88.000000,41.000000,235.000000,39.300000,0.704,27,0
21,8,99,84.000000,20.536458,79.799479,35.400000,0.388,50,0
22,7,196,90.000000,20.536458,79.799479,39.800000,0.451,41,1
23,9,119,80.000000,35.000000,79.799479,29.000000,0.263,29,1
24,11,143,94.000000,33.000000,146.000000,36.600000,0.254,51,1
25,10,125,70.000000,26.000000,115.000000,31.100000,0.205,41,1
26,7,147,76.000000,20.536458,79.799479,39.400000,0.257,43,1
27,1,97,66.000000,15.000000,140.000000,23.200000,0.487,22,0
28,13,145,82.000000,19.000000,110.000000,22.200000,0.245,57,0
29,5,117,92.000000,20.536458,79.799479,34.100000,0.337,38,0
...,...,...,...,...,...,...,...,...,...
738,2,99,60.000000,17.000000,160.000000,36.600000,0.453,21,0
739,1,102,74.000000,20.536458,79.799479,39.500000,0.293,42,1
740,11,120,80.000000,37.000000,150.000000,42.300000,0.785,48,1
741,3,102,44.000000,20.000000,94.000000,30.800000,0.400,26,0
742,1,109,58.000000,18.000000,116.000000,28.500000,0.219,22,0
743,9,140,94.000000,20.536458,79.799479,32.700000,0.734,45,1
744,13,153,88.000000,37.000000,140.000000,40.600000,1.174,39,0
745,12,100,84.000000,33.000000,105.000000,30.000000,0.488,46,0
746,1,147,94.000000,41.000000,79.799479,49.300000,0.358,27,1
747,1,81,74.000000,41.000000,57.000000,46.300000,1.096,32,0
748,3,187,70.000000,22.000000,200.000000,36.400000,0.408,36,1
749,6,162,62.000000,20.536458,79.799479,24.300000,0.178,50,1
750,4,136,70.000000,20.536458,79.799479,31.200000,1.182,22,1
751,1,121,78.000000,39.000000,74.000000,39.000000,0.261,28,0
752,3,108,62.000000,24.000000,79.799479,26.000000,0.223,25,0
753,0,181,88.000000,44.000000,510.000000,43.300000,0.222,26,1
754,8,154,78.000000,32.000000,79.799479,32.400000,0.443,45,1
755,1,128,88.000000,39.000000,110.000000,36.500000,1.057,37,1
756,7,137,90.000000,41.000000,79.799479,32.000000,0.391,39,0
757,0,123,72.000000,20.536458,79.799479,36.300000,0.258,52,1
758,1,106,76.000000,20.536458,79.799479,37.500000,0.197,26,0
759,6,190,92.000000,20.536458,79.799479,35.500000,0.278,66,1
760,2,88,58.000000,26.000000,16.000000,28.400000,0.766,22,0
761,9,170,74.000000,31.000000,79.799479,44.000000,0.403,43,1
762,9,89,62.000000,20.536458,79.799479,22.500000,0.142,33,0
763,10,101,76.000000,48.000000,180.000000,32.900000,0.171,63,0
764,2,122,70.000000,27.000000,79.799479,36.800000,0.340,27,0
765,5,121,72.000000,23.000000,112.000000,26.200000,0.245,30,0
766,1,126,60.000000,20.536458,79.799479,30.100000,0.349,47,1
767,1,93,70.000000,31.000000,79.799479,30.400000,0.315,23,0

In [13]:
new_data_set = pima_indians_ds.copy()
new_data_set.head()

,pregnant_times,glucose_conc,blood_pressure,triceps_thickness,serum_insulin,bmi,diabetes_pedigree,age,class_variable
0,6,148,72.000000,35.000000,79.799479,33.600000,0.627,50,1
1,1,85,66.000000,29.000000,79.799479,26.600000,0.351,31,0
2,8,183,64.000000,20.536458,79.799479,23.300000,0.672,32,1
3,1,89,66.000000,23.000000,94.000000,28.100000,0.167,21,0
4,0,137,40.000000,35.000000,168.000000,43.100000,2.288,33,1
5,5,116,74.000000,20.536458,79.799479,25.600000,0.201,30,0
6,3,78,50.000000,32.000000,88.000000,31.000000,0.248,26,1
7,10,115,69.105469,20.536458,79.799479,35.300000,0.134,29,0
8,2,197,70.000000,45.000000,543.000000,30.500000,0.158,53,1
9,8,125,96.000000,20.536458,79.799479,31.992578,0.232,54,1
10,4,110,92.000000,20.536458,79.799479,37.600000,0.191,30,0
11,10,168,74.000000,20.536458,79.799479,38.000000,0.537,34,1
12,10,139,80.000000,20.536458,79.799479,27.100000,1.441,57,0
13,1,189,60.000000,23.000000,846.000000,30.100000,0.398,59,1
14,5,166,72.000000,19.000000,175.000000,25.800000,0.587,51,1
15,7,100,69.105469,20.536458,79.799479,30.000000,0.484,32,1
16,0,118,84.000000,47.000000,230.000000,45.800000,0.551,31,1
17,7,107,74.000000,20.536458,79.799479,29.600000,0.254,31,1
18,1,103,30.000000,38.000000,83.000000,43.300000,0.183,33,0
19,1,115,70.000000,30.000000,96.000000,34.600000,0.529,32,1
20,3,126,88.000000,41.000000,235.000000,39.300000,0.704,27,0
21,8,99,84.000000,20.536458,79.799479,35.400000,0.388,50,0
22,7,196,90.000000,20.536458,79.799479,39.800000,0.451,41,1
23,9,119,80.000000,35.000000,79.799479,29.000000,0.263,29,1
24,11,143,94.000000,33.000000,146.000000,36.600000,0.254,51,1
25,10,125,70.000000,26.000000,115.000000,31.100000,0.205,41,1
26,7,147,76.000000,20.536458,79.799479,39.400000,0.257,43,1
27,1,97,66.000000,15.000000,140.000000,23.200000,0.487,22,0
28,13,145,82.000000,19.000000,110.000000,22.200000,0.245,57,0
29,5,117,92.000000,20.536458,79.799479,34.100000,0.337,38,0
...,...,...,...,...,...,...,...,...,...
738,2,99,60.000000,17.000000,160.000000,36.600000,0.453,21,0
739,1,102,74.000000,20.536458,79.799479,39.500000,0.293,42,1
740,11,120,80.000000,37.000000,150.000000,42.300000,0.785,48,1
741,3,102,44.000000,20.000000,94.000000,30.800000,0.400,26,0
742,1,109,58.000000,18.000000,116.000000,28.500000,0.219,22,0
743,9,140,94.000000,20.536458,79.799479,32.700000,0.734,45,1
744,13,153,88.000000,37.000000,140.000000,40.600000,1.174,39,0
745,12,100,84.000000,33.000000,105.000000,30.000000,0.488,46,0
746,1,147,94.000000,41.000000,79.799479,49.300000,0.358,27,1
747,1,81,74.000000,41.000000,57.000000,46.300000,1.096,32,0
748,3,187,70.000000,22.000000,200.000000,36.400000,0.408,36,1
749,6,162,62.000000,20.536458,79.799479,24.300000,0.178,50,1
750,4,136,70.000000,20.536458,79.799479,31.200000,1.182,22,1
751,1,121,78.000000,39.000000,74.000000,39.000000,0.261,28,0
752,3,108,62.000000,24.000000,79.799479,26.000000,0.223,25,0
753,0,181,88.000000,44.000000,510.000000,43.300000,0.222,26,1
754,8,154,78.000000,32.000000,79.799479,32.400000,0.443,45,1
755,1,128,88.000000,39.000000,110.000000,36.500000,1.057,37,1
756,7,137,90.000000,41.000000,79.799479,32.000000,0.391,39,0
757,0,123,72.000000,20.536458,79.799479,36.300000,0.258,52,1
758,1,106,76.000000,20.536458,79.799479,37.500000,0.197,26,0
759,6,190,92.000000,20.536458,79.799479,35.500000,0.278,66,1
760,2,88,58.000000,26.000000,16.000000,28.400000,0.766,22,0
761,9,170,74.000000,31.000000,79.799479,44.000000,0.403,43,1
762,9,89,62.000000,20.536458,79.799479,22.500000,0.142,33,0
763,10,101,76.000000,48.000000,180.000000,32.900000,0.171,63,0
764,2,122,70.000000,27.000000,79.799479,36.800000,0.340,27,0
765,5,121,72.000000,23.000000,112.000000,26.200000,0.245,30,0
766,1,126,60.000000,20.536458,79.799479,30.100000,0.349,47,1
767,1,93,70.000000,31.000000,79.799479,30.400000,0.315,23,0

In [14]:
new_data_set.to_csv('data/pima-indians-diabetes.new-data.csv')